apiVersion: v1
kind: Service
metadata:
  name: users-db
spec:
  ports:
  - port: 27017
    name: tcp
  selector:
    app: users-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-db
      version: v1
  template:
    metadata:
      labels:
        app: users-db
        version: v1
    spec:
      containers:
      - name: users-db
        image: mongo
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: users-service 
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: users
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
      version: v1
  template:
    metadata:
      labels:
        app: users
        version: v1
    spec:
      containers:
      - name: users
        image: roostergr/users-service:v1
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_HOST
          value: users-db
