# This is a basic workflow to help you get started with Actions

name: Docker Build

# Controls when the workflow will run
on: [push]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: docker build python
        run: |
          docker build ./ -t roostergr/users-service:v1
      - name: docker push
        run: |
           docker push roostergr/users-service:v1
